version: "3.9"
services:
  runner:
    build:
      context: build
      dockerfile: Dockerfile
    restart: unless-stopped
    # Change this to what you want your runner to be called!
    hostname: docker_runner
    environment:
      # Required for the first run only!
      - GITHUB_TOKEN="<token>"
      # Same here!
      - GITHUB_REPOSITORY="<repo url>"
    volumes:
      # We do this to save the runner and not have to download the runner each time.
      - "./work:/home/runner:rw"
